baseURL = 'https://t24.co/'
languageCode = 'en-us'
title = 'tarper24 Lynx'

[module]
[[module.imports]]
  path = 'github.com/tarper24/lynx'

[taxonomies]

[author]
  name = "tarper24"
  headline = "Just a gaming furry flying through the internet."
  image = "images/avatar.png"

  links = [
    { my-website = { href = "https://tarper24.com", text = "My website and blog" } },
    { mastodon = { href = "https://social.pawsitiv.space/@tarper24", text = "Pawsitiv Space (Mastodon)" } },
    { youtube = "https://yt.t24.co" },
    { twitch = "https://tv.t24.co" },
    { github = "https://gh.t24.co" },
    { telegram = "https://t.me/tarper24" },
    { discord = { text = "tarper24" } }
  ]
