baseURL = 'https://t24.co/'
languageCode = 'en-us'
title = 'tarper24 Lynx'

[module]
[[module.imports]]
  path = 'github.com/tarper24/lynx'

[taxonomies]

[author]
  name = "tarper24"
  headline = "Just a gaming furry flying through the internet."
  image = "images/avatar.png"
